apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-storage-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-storage-service
  template:
    metadata:
      labels:
        app: data-storage-service
    spec:
      containers:
        - name: data-storage-service
          image: developeriq.azurecr.io/github-metrics-service:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: data-storage-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: data-storage-service



